### PR TITLE
{Jest Tests} Implementing Jest Testing to Github Workflows

### PR DESCRIPTION
**Pull request by RafaelHerrero**
## Related Issue

- Fixes # (issue)

## Proposed Changes 

Adding Jest Test to github actions to test our code everytime that a new PR is opened and a new push to main is made.
Also included a initial test file called `test_file.js` for testing since we don't have any tests yet

## Additional Info

Jest website: https://jestjs.io/docs/getting-started

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

### CODE REVIEW

**Review by AbhijithGanesh — APPROVED** [review]
Looks good to me

**Comment by AbhijithGanesh** [comment]
@yashgangwar7558 Can you review this as well

**Review by yashgangwar7558 — APPROVED** [review]

**Comment by AmitKarnam** [comment]
LGTM!

**Review by AmitKarnam — APPROVED** [review]
LGTM!

**Pull request merged**
